In [1]:
import pandas as pd

In [2]:
import pandas as pd

df = pd.read_csv("Placement_Data_Full_Class.csv")

In [3]:
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [4]:
# Display basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [5]:
# Check missing values in each column
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [6]:
# Check for duplicate records
df.duplicated().sum()

np.int64(0)

In [7]:
# Fill missing salary values with 0
# Students who were not placed do not have a salary.

df['salary'] = df['salary'].fillna(0)

In [8]:
# Check missing values again

df.isnull().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [9]:
# Clean text columns

text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip().str.title()

In [10]:
# Rename columns for better readability

df.rename(columns={
    'ssc_p': 'ssc_percentage',
    'hsc_p': 'hsc_percentage',
    'degree_p': 'degree_percentage',
    'etest_p': 'etest_percentage',
    'mba_p': 'mba_percentage'
}, inplace=True)

In [11]:
# Create a new column based on salary

df['salary_category'] = df['salary'].apply(
    lambda x: 'High' if x >= 500000 else ('Medium' if x > 0 else 'Not Placed')
)

In [12]:
# Save the cleaned dataset

df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [13]:
# Rename columns for better readability

df.rename(columns={
    'ssc_p': 'ssc_percentage',
    'hsc_p': 'hsc_percentage',
    'degree_p': 'degree_percentage',
    'etest_p': 'etest_percentage',
    'mba_p': 'mba_percentage'
}, inplace=True)

In [14]:
# Create a new salary category column

df['salary_category'] = df['salary'].apply(
    lambda x: 'High' if x >= 500000 else ('Medium' if x > 0 else 'Not Placed')
)

In [15]:
# Display the first 5 rows

df.head()

,sl_no,gender,ssc_percentage,ssc_b,hsc_percentage,hsc_b,hsc_s,degree_percentage,degree_t,workex,etest_percentage,specialisation,mba_percentage,status,salary,salary_category
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&Hr,58.80,Placed,270000.0,Medium
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,Medium
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0,Medium
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&Hr,59.43,Not Placed,0.0,Not Placed
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0,Medium

In [16]:
# Save the cleaned dataset

df.to_csv("cleaned_dataset.csv", index=False)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!